app.version=${project.version}
app.name=${project.parent.name}
app.build.timestamp=${maven.build.timestamp}
github.url=https://github.com/olehsvyrydov/selfemploy-uk
github.releasesApiUrl=https://api.github.com/repos/olehsvyrydov/selfemploy-uk/releases/latest
